org.gradle.jvmargs=-Xmx2G

# Fabric (https://fabricmc.net/versions.html)
minecraft_version=26.1.2
loader_version=0.19.3
loom_version=1.16-SNAPSHOT

# Mod Properties
mod_version=1.5.0
maven_group=com.kkllffaa
archives_base_name=meteor-litematica-printer

# litematica
litematica_version = 0.27.8
malilib_version = 0.28.8
